environment:
  AUTOMATED_CI_TESTING: 1
  matrix:
    - perl: default
      W32MNPP_FORCE_VER: v8.9.6.4
    - perl: 5.20.3.3

skip_tags: true

cache:
  #- C:\strawberry -> appveyor.yml

install:
  - IF NOT DEFINED myBits ( set myBits= & echo myBits equals space )
  - echo myBits=_%myBits%_
  #- cinst %myBits% notepadplusplus
  - IF NOT DEFINED perl set perl=default
  - echo install Perl v%perl%...
  - IF /I %perl%==default (cinst %myBits% strawberryperl) ELSE (cinst %myBits% strawberryperl --version %perl%)
  - IF NOT EXIST "chocologs" MKDIR chocologs
  - IF EXIST "c:\ProgramData\chocolatey\logs" COPY /Y "c:\ProgramData\chocolatey\logs" "chocologs"
  - set PATH=C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
  - cd %APPVEYOR_BUILD_FOLDER%
  - perl -le "print qq(installed perl v$])"
  - IF NOT EXIST c:\strawberry\perl\bin\cpanm.bat ( cpan -i App::cpanminus )
  # update cpanm to make sure it's new enough for installdeps to work
  - cpanm App::cpanminus
  - IF EXIST "C:\Users\appveyor\.cpanm\build.log" ( (TYPE "C:\Users\appveyor\.cpanm\build.log" >> cpanm.build.log ) & (DEL "C:\Users\appveyor\.cpanm\build.log") )
  # make sure MakeMaker is new enough on v5.10, but not too new to install; unfortunately, test suite fails, so use --notest
  - echo "%perl%" LSS "5.12"
  - IF /I %perl% LSS 5.12 ( perl "-MExtUtils::MakeMaker" -le "print $ExtUtils::MakeMaker::VERSION" & cpanm "--notest" "ExtUtils::MakeMaker@6.98" & perl "-MExtUtils::MakeMaker" -le "print $ExtUtils::MakeMaker::VERSION" )
  - IF EXIST "C:\Users\appveyor\.cpanm\build.log" ( (TYPE "C:\Users\appveyor\.cpanm\build.log" >> cpanm.build.log ) & (DEL "C:\Users\appveyor\.cpanm\build.log") )
  # these need a particular order, so do them manually; Encode::compat hangs in test suite, so run all these with --notest for speed
  # use --verbose --no-interactive if I want to debug cpanm logs even without
  #- set VERBOSE=--verbose --no-interactive
  - set VERBOSE= &echo empty
  - IF /I %perl% LSS 5.14 ( cpanm --notest %VERBOSE% Config::Perl::V Encode::compat & echo ordered install done, no bombout )
  - IF EXIST "C:\Users\appveyor\.cpanm\build.log" ( (TYPE "C:\Users\appveyor\.cpanm\build.log" >> cpanm.build.log ) & (DEL "C:\Users\appveyor\.cpanm\build.log") )
  - IF /I %perl% LSS 5.14 ( cpanm %VERBOSE% Math::Int64 & echo ordered install 2 done, no bombout )
  - IF EXIST "C:\Users\appveyor\.cpanm\build.log" ( (TYPE "C:\Users\appveyor\.cpanm\build.log" >> cpanm.build.log ) & (DEL "C:\Users\appveyor\.cpanm\build.log") )
  - IF /I %perl% LSS 5.14 ( cpanm %VERBOSE% Win32::API & echo ordered install 3 done, no bombout )
  - IF EXIST "C:\Users\appveyor\.cpanm\build.log" ( (TYPE "C:\Users\appveyor\.cpanm\build.log" >> cpanm.build.log ) & (DEL "C:\Users\appveyor\.cpanm\build.log") )
  # _now_ install the dependencies (--notest for speed)
  - cpanm --installdeps --notest %VERBOSE% . & echo no bombout
  - IF EXIST "C:\Users\appveyor\.cpanm\build.log" ( (TYPE "C:\Users\appveyor\.cpanm\build.log" >> cpanm.build.log ) & (DEL "C:\Users\appveyor\.cpanm\build.log") )

build_script:
  - echo build using Perl=%perl%...
  - perl -le "print qq(build with perl v$])"
  ## make: but don't want to have to know whether strawberry is using dmake, gmake, or futuremake
  ## ->doesn't actually matter; if you use cpanm --test-only for running the test suite, cpanm will handle the right make for the build process
  ## ->keep the commented version for future reference
  #- if exist "Makefile.PL" (perl Makefile.PL)
  #- if exist "Makefile"    (perl -MConfig -le "system $Config{make}")
  #- if exist "Makefile"    (perl -MConfig -le "print qq($Config{make} test)" > mytest.bat) ELSE ( echo prove -l t > mytest.bat)
  - echo build done

after_build:
  - IF EXIST "c:\users\appveyor\.cpanm\work\" (MOVE /Y c:\users\appveyor\.cpanm\work .)

test_script:
  - echo .....................................................
  - echo test Perl=%perl%...
  - perl -le "print qq(test with perl v$])"
  - perl -V:ptrsize -V:ivsize -V:myuname
  #- perl Makefile.PL && prove -l t
  - cpanm --test-only --verbose --no-interactive .

artifacts:
  - path: cpanm.build.log
  - path: work\**\*.log
