# This is a basic workflow to help you get started with Actions
# use [tobyink]'s https://github.com/tobyink/p5-exporter-tiny/blob/master/.github/workflows/ci.yml as a reference
# - for testing, don't need the "dist" job, because I don't need the tarball; I can just run tests from the repo checkout
# - eventually, might want to add back in a "dist", which creates and archives the tarball during a tag
#   -- that probably won't work, because of gpg signing

name: perl-ci

# Controls when the workflow will run
on:
  # Triggers the workflow on all pushes to branches, and pull request for the main branch
  push:
    branches:

  ## pull_request:
  ##   branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: Test With Perl ${{ matrix.perl }} ${{ matrix.os }} ${{ matrix.joblabel }}
    runs-on: ${{ ( ( startsWith(matrix.os, 'ubuntu:') && 'ubuntu-latest' ) || ( startsWith(matrix.os, 'macos:') && 'macos-latest' ) || startsWith(matrix.os, 'windows') && 'windows-latest' ) || matrix.os }}
    env:
      AUTOMATED_CI_TESTING: 1
    strategy:
      fail-fast: false
      matrix:
        os:                 ['windows:strawberry']
        perl:               ['5.36', '5.42']
        include:
          - perl: '5.14'
            os: 'windows-latest'
            W32MNPP_FORCE_VER: 'v8.9.6.4'
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set up perl ${{ matrix.perl }} ${{ matrix.os }} ${{ matrix.joblabel }}
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
          multi-thread: ${{ ( ( startsWith(matrix.os, 'windows') || endsWith(matrix.os, ':thr') ) && true ) || false }}
          distribution: ${{ ( endsWith(matrix.os, ':strawberry') && 'strawberry' ) || 'default' }}
      - name: restore-cache
        id: perl-cache-restore
        uses: actions/cache/restore@v6
        with:
            path: |
                c:\hostedtoolcache\windows\strawberry-perl
                C:\hostedtoolcache\windows\perl
            key: ${{ matrix.os }}-${{ matrix.perl }}
      - name: Find binaries expecting  ${{ matrix.perl }} ${{ matrix.os }} ${{ matrix.joblabel }}
        run: |
            Write-Host "`n====================`nFinding perl.exe"
            ${{ ( startsWith(matrix.os, 'windows') && '(get-command perl).Path'  ) || 'which perl' }}
            perl -v
            Write-Host "`n--------------------`nFinding cpanm.bat"
            ${{ ( startsWith(matrix.os, 'windows') && '(get-command cpanm).Path' ) || 'which cpanm' }}
            cpanm --version
      - name: Pre-Makefile.PL prereqs
        run: |
            Write-Host "`n--------------------`nExtUtils::MakeMaker:"
            cpanm ExtUtils::MakeMaker@7.76
            Write-Host "`n--------------------`HTTP::Tiny:"
            cpanm HTTP::Tiny~0.055
            # these seem to have difficulty getting automatically installed as preqreqs in earlier perl versions, so might manually do them if I start supporting older perls again
            # cpanm Config::Perl::V Encode::compat Math::Int64
      - name: Run Makefile.PL and get prereqs
        env:
          W32MNPP_FORCE_VER: ${{ matrix.W32MNPP_FORCE_VER }}
        # but there might be some modules needed by configure, which makes chicken/egg problem
        run: |
            Write-Host "`n--------------------`n# initially grab the prereqs for Makefile.PL"
            cpanm --notest File::Which File::Spec File::Fetch Archive::Extract Archive::Zip
            Write-Host "`n--------------------`n# intial run of Makefile.PL to see missing dependencies"
            perl Makefile.PL
            cpanm --notest --installdeps .
            Write-Host "`n--------------------`n# re-run Makefile.PL after dependencies met"
            perl Makefile.PL
      - name: save-cache
        id: perl-cache-save
        uses: actions/cache/save@v6
        with:
            path: |
                c:\hostedtoolcache\windows\strawberry-perl
                C:\hostedtoolcache\windows\perl
            key: ${{ steps.perl-cache-restore.outputs.cache-primary-key }}
      - name: cpanm test-only
        env:
          W32MNPP_FORCE_VER: ${{ matrix.W32MNPP_FORCE_VER }}
        run: |
          cpanm --test-only --verbose --no-interactive .
      #- name: verbose prove (for debug)
      #  env:
      #    W32MNPP_FORCE_VER: ${{ matrix.W32MNPP_FORCE_VER }}
      #  run: |
      #      prove -vl t
      - name: Run and report test coverage
        if: ${{ matrix.coverage }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cpanm -n Devel::Cover::Report::Coveralls
          cover -test -report Coveralls
#
